server:
  port: 9001

logging:
  level:
    org.springframework.web: "trace"
    org.springframework: "debug"

spring:
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9001