#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/userCrud
#    username: bhaskar
#    password: bhaskar
#  jpa:
#    hibernate:
#      ddl-auto: <create | create-drop | update | validate | none>
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/userCrud
      username: bhaskar
      password: bhaskar
      pool-size: 30

server:
  port: 9090
  error:
    include-binding-errors: always
    include-message: always